export const restaurants = [
  {
    title: "Sushi Bar",
    location: "Gdynia",
    id: 8,
    phoneNr: 583444555,
    email: "sushi@mail.com",
    address: "Kościuszki 4",
    tags: ["japanese", "asian", "sushi"],
    rating: 4.8,
    priceLvl: 2,
    img: "sushi",
    price: 39,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut consectetur adipiscing elit, Ut enim ad minim veniam. Ut enim ad minim veniam. Ut enim ad minim veniam. Ut enim ad minim veniam. sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Ut enim ad minim veniam.Ut enim ad minim veniam.Ut enim ad minim veniam. ",
  },
  {
    title: "Willowa",
    location: "Gdańsk",
    id: 1,
    phoneNr: 607345234,
    email: "willowa@mail.com",
    address: "Stoczniowa 32",
    tags: ["vege", "european"],
    rating: 3.4,
    priceLvl: 5,
    img: "plates",
    price: 79,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Ut enim ad minim veniam.",
  },
  {
    title: "Taste of India",
    location: "Warszawa",
    id: 7,
    phoneNr: 506111222,
    email: "indian@mail.com",
    address: "Nowogrodzka 22",
    tags: ["indian", "asian", "chicken"],
    rating: 4.5,
    priceLvl: 2,
    img: "indian",
    price: 19,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore Ut enim ad minim veniam. magna aliqua. Ut enim ad minim veniam.",
  },
  {
    title: "Jack's Kitchen",
    location: "Kraków",
    id: 2,
    phoneNr: 606111222,
    email: "kowalski@mail.com",
    address: "Nowa 12",
    tags: ["european"],
    rating: 4.7,
    priceLvl: 4,
    price: 49,
    img: "tomatoes",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, Ut enim ad minim veniam. sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.",
  },
  {
    title: "Healthy Bites",
    location: "Kraków",
    id: 6,
    phoneNr: 605222333,
    email: "healthybites@mail.com",
    address: "Świętej Agnieszki 14",
    tags: ["healthy", "european"],
    rating: 4.8,
    priceLvl: 5,
    img: "plates2",
    price: 99,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, Ut enim ad minim veniam. Ut enim ad minim veniam. sed do consectetur adipiscing elit, Ut enim ad minim veniam. Ut enim ad minim veniam. Ut enim ad minim veniam. Ut enim ad minim veniam. sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.",
  },
  {
    title: "Pizza Gaggetta",
    location: "Wrocław",
    id: 4,
    phoneNr: 708222333,
    email: "pizza@mail.com",
    address: "Łąkowa 8",
    tags: ["italian", "fast food"],
    rating: 4.9,
    priceLvl: 3,
    price: 45,
    img: "pizza",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.",
  },
  {
    title: "Polish Bakery",
    location: "Kraków",
    id: 5,
    phoneNr: 604555666,
    email: "bakery@mail.com",
    address: "Cicha 6",
    tags: ["bakery", "breakfast"],
    rating: 4.0,
    price: 9,
    priceLvl: 1,
    img: "coffee",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.",
  },
  {
    title: "Burger Palace",
    location: "Warszawa",
    id: 3,
    phoneNr: 505333444,
    email: "burger@mail.com",
    address: "Polna 22",
    tags: ["american", "fast food", "burger"],
    rating: 4.2,
    price: 39,
    priceLvl: 4,
    img: "barbecue",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, Ut enim ad minim veniam. Ut enim ad minim veniam. Ut enim ad minim veniam. Ut enim ad minim veniam. sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. consectetur adipiscing elit, Ut enim ad minim veniam. Ut enim ad minim veniam. Ut enim ad minim veniam. Ut enim ad minim veniam. sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.",
  },
];

export const hotels = [
  {
    title: "Lagoon Hotel",
    location: "Awrens",
    id: 8,
    phoneNr: 583444555,
    email: "lagoon@mail.com",
    address: "Kościuszki 4",
    tags: ["pool", "AC", "bar"],
    rating: 4.8,
    priceLvl: 2,
    img: "lagoon",
    price: 39,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut consectetur adipiscing elit, Ut enim ad minim veniam. Ut enim ad minim veniam. Ut enim ad minim veniam. Ut enim ad minim veniam. sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Ut enim ad minim veniam.Ut enim ad minim veniam.Ut enim ad minim veniam. ",
  },
  {
    title: "Mountain View Hotel",
    location: "Zakopane",
    id: 9,
    phoneNr: 583444556,
    email: "mountainview@mail.com",
    address: "Piłsudskiego 3",
    tags: ["mountain view", "spa", "skiing"],
    rating: 4.5,
    priceLvl: 3,
    img: "mountainview",
    price: 120,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
  },
  {
    title: "Seaside Suites",
    location: "Miami",
    id: 15,
    phoneNr: 987654321,
    email: "seaside@mail.com",
    address: "456 Ocean Blvd",
    tags: ["beachfront", "pool", "ocean views", "tropical"],
    rating: 4.6,
    priceLvl: 4,
    img: "seaside",
    price: 299,
    description:
      "Escape to our tropical paradise and experience the ultimate beachfront vacation. Our suites offer stunning ocean views and private balconies, while our pool and beach club provide endless entertainment. With on-site dining options and luxurious amenities, you'll never want to leave.",
  },
  {
    title: "Mariott",
    location: "Warszawa",
    id: 16,
    phoneNr: 987654321,
    email: "mariott@mail.com",
    address: "456 Ocean Blvd",
    tags: ["beachfront", "pool", "ocean views", "tropical"],
    rating: 4.6,
    priceLvl: 4,
    img: "mariott",
    price: 299,
    description:
      "Escape to our tropical paradise and experience the ultimate beachfront vacation. Our suites offer stunning ocean views and private balconies, while our pool and beach club provide endless entertainment. With on-site dining options and luxurious amenities, you'll never want to leave.",
  },
];

export const attractions = [
  {
    title: "Energy Theme Park",
    location: "Kraków",
    id: 8,
    phoneNr: 583444555,
    email: "energy@mail.com",
    address: "Kościuszki 4",
    tags: ["restaurants", "hotels", "bars"],
    rating: 4.8,
    priceLvl: 2,
    img: "energy",
    price: 39,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut consectetur adipiscing elit, Ut enim ad minim veniam. Ut enim ad minim veniam. Ut enim ad minim veniam. Ut enim ad minim veniam. sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Ut enim ad minim veniam.Ut enim ad minim veniam.Ut enim ad minim veniam. ",
  },
  {
    title: "Adventure Park",
    location: "Berlin",
    id: 5,
    phoneNr: 4930304050,
    email: "adventure@mail.com",
    address: "Brandenburgische Str. 15",
    tags: ["outdoor activities", "camping"],
    rating: 4.2,
    priceLvl: 3,
    img: "adventure",
    price: 49,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut consectetur adipiscing elit, Ut enim ad minim veniam. Ut enim ad minim veniam. Ut enim ad minim veniam. Ut enim ad minim veniam. sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
  },
  {
    title: "Historic Castle",
    location: "Edinburgh",
    id: 12,
    phoneNr: 441312279000,
    email: "castle@mail.com",
    address: "Castlehill, Edinburgh",
    tags: ["sightseeing", "history"],
    rating: 4.6,
    priceLvl: 4,
    img: "castle",
    price: 69,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut consectetur adipiscing elit, Ut enim ad minim veniam. Ut enim ad minim veniam. Ut enim ad minim veniam. Ut enim ad minim veniam. sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Ut enim ad minim veniam.Ut enim ad minim veniam. ",
  },
  {
    title: "Bowling Den",
    location: "Phuket",
    id: 3,
    phoneNr: 6676374182,
    email: "bowling@mail.com",
    address: "Kamala, Thailand",
    tags: ["bowling", "swimming", "darts"],
    rating: 4.9,
    priceLvl: 5,
    img: "bowling",
    price: 199,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut consectetur adipiscing elit, Ut enim ad minim veniam. Ut enim ad minim veniam. Ut enim ad minim veniam. Ut enim ad minim veniam. sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Ut enim ad minim veniam.Ut enim ad minim veniam. Ut enim ad minim veniam. Ut enim ad minim veniam. Ut enim ad minim veniam. Ut enim ad minim veniam. Ut enim ad minim veniam. Ut enim",
  },
];
